version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db  
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  db:
    image: "postgres:12"

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:  
  db-data:

